### ISSUE TITLE
[BUG] Color picker error

### ISSUE THREAD

**Issue by foxwyn** [anodyne/nova3#371]
**Describe the bug**
Selecting Phlox in the color shade picker causes an error. This occured while messing about on the beta site.

Here is the generated error log: [Flareapp Error Dump](https://flareapp.io/share/17WJvKnP)

**To Reproduce**
1. Go to settings/appearance
2. Try setting any of the color options to "Phlox"
3. See error

**Expected behavior**
The color to be selected and set as Phlox without an error.

**Comment by agentphoenix** [comment]
Thanks for the report @foxwyn. There are some updates going out today that should fix a bunch of errors. (Though Phlox has been removed from the colors list since it was almost identical to another color.)

**Comment by foxwyn** [comment]
@agentphoenix Well, if anything, I learned a new color name haha

**Comment by agentphoenix** [comment]
@foxwyn The demo site has been updated, so let me know if you still see errors.
